[build-system]
requires = ['setuptools>=42', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'estimpy'
version = '2.0.0'
description = 'A package for Estim audio playback and visualization'
readme = 'README.md'
license = {text = 'MIT'}
authors = [
    {name = 'Psynapse', email = 'psynapse@psynapse.gay'}
]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: X11 Applications :: Qt',
    'Intended Audience :: End Users/Desktop',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Topic :: Multimedia :: Sound/Audio',
    'Topic :: Multimedia :: Sound/Audio :: Analysis',
    'Topic :: Scientific/Engineering :: Visualization',
]
requires-python = '>=3.11'

[project.optional-dependencies]
dev = ['pytest']

dependencies = [
    'audioop-lts; python_version >= "3.13"',
    'colorama',
    'matplotlib>=3.7.2',
    'mutagen',
    'numpy',
    'pillow',
    'pydub',
    'pygame-ce',
    'pyqt6',
    'pyyaml',
    'scipy',
    'tqdm'
]

[project.urls]
Homepage = 'https://github.com/PsynApps/estimpy'
Documentation = 'https://github.com/PsynApps/estimpy/blob/main/README.md'
Source = 'https://github.com/PsynApps/estimpy'
Tracker = 'https://github.com/PsynApps/estimpy/issues'
Changelog = 'https://github.com/PsynApps/estimpy/blob/main/CHANGELOG.md'
Discussions = 'https://github.com/PsynApps/estimpy/discussions'
PyPI = 'https://pypi.org/project/estimpy/'

[project.entry-points.console_scripts]
estimpy = 'estimpy.cli:main'

[tool.setuptools.packages.find]
exclude = ['assets*', 'export*', 'tests*']

[tool.setuptools.package-data]
estimpy = ['config/*.yaml']

[tool.pytest.ini_options]
testpaths = ['tests']