---
estimpy-version: 2.0.0
visualization:
  image:
    display:
      title:
        enabled: False
    export:
      title:
        enabled: False
  video:
    display:
      title:
        enabled: False
    export:
      title:
        enabled: False
