---
estimpy-version: 2.0.0
video:
  export:
    codec: libx264
    ffmpeg-extra-args:
      '-pix_fmt': 'yuv420p'
      '-crf': 30
      '-profile:v': 'high'
      '-level': 3.1
visualization:
  image:
    export:
      size: 1136x640
  style:
    axes:
      font-size: 32
    time:
      font-size: 48
  video:
    export:
      size: 1136x640
    window-length: 10
