---
visualization:
  video:
    export:
      codec: hevc_videotoolbox
      ffmpeg-extra-args:
        '-crf': ~
        '-preset': ~
        '-tune': ~
        '-q:v': 60
        '-tag:v': 'hvc1'
        '-profile:v': 'main10'