---
estimpy-version: 2.0.0
visualization:
  image:
    export:
      size: 7680x4320
  video:
    export:
      ffmpeg-extra-args:
        '-tile-columns': 3
        '-tile-rows': 2
      segment-length: 300
      size: 7680x4320