---
estimpy-version: 2.0.0
visualization:
  video:
    export:
      codec: av1_nvenc
      ffmpeg-extra-args:
        '-crf': ~
        '-pix_fmt': 'yuv420p10le'
        '-cq': 28
        '-preset': p6
        '-tune': hq
        '-spatial-aq': 1