---
visualization:
  video:
    export:
      codec: hevc_nvenc
      ffmpeg-extra-args:
        '-crf': ~                                                                                                                                                                                           
        '-cq': 22                                                                  
        '-preset': slow
        '-tune': hq
        '-spatial-aq': 1