---
visualization:
  video:
    export:
      codec: libvpx-vp9
      ffmpeg-extra-args:
        '-preset': ~                                                                                                                                                                                        
        '-tune': ~
        '-b:v': 0
        '-crf': 30
        '-cpu-used': 3
        '-row-mt': 1